//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursework.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coursework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сокращение.
        /// </summary>
        internal static string AbbreviationAssetNameType {
            get {
                return ResourceManager.GetString("AbbreviationAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сокращение.
        /// </summary>
        internal static string AbbreviationMarketNameType {
            get {
                return ResourceManager.GetString("AbbreviationMarketNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        internal static string CountryAssetNameType {
            get {
                return ResourceManager.GetString("CountryAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        internal static string CountryMarketNameType {
            get {
                return ResourceManager.GetString("CountryMarketNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        internal static string CurrenyAssetNameType {
            get {
                return ResourceManager.GetString("CurrenyAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый актив ({0}).
        /// </summary>
        internal static string DefaultNameNewAsset {
            get {
                return ResourceManager.GetString("DefaultNameNewAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая биржа ({0}).
        /// </summary>
        internal static string DefaultNameNewMarket {
            get {
                return ResourceManager.GetString("DefaultNameNewMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрана биржа для добавления  актива.
        /// </summary>
        internal static string ErroeMessageWarningNotSelectedMarket {
            get {
                return ResourceManager.GetString("ErroeMessageWarningNotSelectedMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран текущий актив.
        /// </summary>
        internal static string ErrorMessageWarningNotExistCurrentAsset {
            get {
                return ResourceManager.GetString("ErrorMessageWarningNotExistCurrentAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет отмеченного актива.
        /// </summary>
        internal static string ErrorMessageWarningNotExistSelectAsset {
            get {
                return ResourceManager.GetString("ErrorMessageWarningNotExistSelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет отмеченной биржи.
        /// </summary>
        internal static string ErrorMessageWarningNotExistSelectMarket {
            get {
                return ResourceManager.GetString("ErrorMessageWarningNotExistSelectMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актив с данным типом создать невозможно.
        /// </summary>
        internal static string ErrorMessageWarningNotExistTypeAsset {
            get {
                return ResourceManager.GetString("ErrorMessageWarningNotExistTypeAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Котировки.
        /// </summary>
        internal static string HeaderQuoteChart {
            get {
                return ResourceManager.GetString("HeaderQuoteChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название инструмента.
        /// </summary>
        internal static string InstrumentAssetNameType {
            get {
                return ResourceManager.GetString("InstrumentAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификационный код рынка.
        /// </summary>
        internal static string MICMarketNameType {
            get {
                return ResourceManager.GetString("MICMarketNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string NameAddButtonForm {
            get {
                return ResourceManager.GetString("NameAddButtonForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string NameAssetNameType {
            get {
                return ResourceManager.GetString("NameAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на checkBox_{0}.
        /// </summary>
        internal static string NameCheckboxFilter {
            get {
                return ResourceManager.GetString("NameCheckboxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на label_{0}.
        /// </summary>
        internal static string NameLabelFilter {
            get {
                return ResourceManager.GetString("NameLabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string NameMarketNameType {
            get {
                return ResourceManager.GetString("NameMarketNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на panel_{0}.
        /// </summary>
        internal static string NamePanelFilter {
            get {
                return ResourceManager.GetString("NamePanelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на radioButton_{0}_{1}.
        /// </summary>
        internal static string NameRadioButtonFilter {
            get {
                return ResourceManager.GetString("NameRadioButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на textBox_{0}.
        /// </summary>
        internal static string NameTextboxFilter {
            get {
                return ResourceManager.GetString("NameTextboxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        internal static string NameTypeAssetNameType {
            get {
                return ResourceManager.GetString("NameTypeAssetNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часовой пояс.
        /// </summary>
        internal static string TimezoneMarketNameType {
            get {
                return ResourceManager.GetString("TimezoneMarketNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        internal static string TypeNameCurrencyAsset {
            get {
                return ResourceManager.GetString("TypeNameCurrencyAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акция обыкновенная.
        /// </summary>
        internal static string TypeNameStockAsset {
            get {
                return ResourceManager.GetString("TypeNameStockAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/stocks?source=docs&amp;exchange={0}.
        /// </summary>
        internal static string URLForDownloadAssetsByMarket {
            get {
                return ResourceManager.GetString("URLForDownloadAssetsByMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/symbol_search?symbol={0}&amp;exchange={1}.
        /// </summary>
        internal static string URLForDownloadAssetsByName {
            get {
                return ResourceManager.GetString("URLForDownloadAssetsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/cryptocurrency_exchanges?source=docs.
        /// </summary>
        internal static string URLForDownloadCryptoMarkets {
            get {
                return ResourceManager.GetString("URLForDownloadCryptoMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/exchanges?name={0}.
        /// </summary>
        internal static string URLForDownloadMarketByName {
            get {
                return ResourceManager.GetString("URLForDownloadMarketByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/exchanges?source=docs.
        /// </summary>
        internal static string URLForDownloadMarkets {
            get {
                return ResourceManager.GetString("URLForDownloadMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.twelvedata.com/time_series?symbol={0}:{1}&amp;timezone={2}&amp;start_date={3}&amp;end_date={4}&amp;interval=30min&amp;apikey={5}.
        /// </summary>
        internal static string URLForDownloadQuotes {
            get {
                return ResourceManager.GetString("URLForDownloadQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит.
        /// </summary>
        internal static string WordContainFilter {
            get {
                return ResourceManager.GetString("WordContainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на =.
        /// </summary>
        internal static string WordEquallyFilter {
            get {
                return ResourceManager.GetString("WordEquallyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не учитывать.
        /// </summary>
        internal static string WordNoLookFilter {
            get {
                return ResourceManager.GetString("WordNoLookFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не содержит.
        /// </summary>
        internal static string WordNotContainFilter {
            get {
                return ResourceManager.GetString("WordNotContainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !=.
        /// </summary>
        internal static string WordNotEquallyFilter {
            get {
                return ResourceManager.GetString("WordNotEquallyFilter", resourceCulture);
            }
        }
    }
}
