//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursework.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAsset
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string InstrumentName { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual TMarket TMarket { get; set; }
    }
}
