//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursework.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMarket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMarket()
        {
            this.TAsset = new HashSet<TAsset>();
        }
    
        public int Id { get; set; }
        public string Abbreviation { get; set; }
        public string Country { get; set; }
        public string MIC { get; set; }
        public string Timezone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAsset> TAsset { get; set; }
        public virtual TAccount Account { get; set; }
    }
}
